default_language_version:
    python: python3.9.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/pycqa/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        types: [ python ]
        exclude: '(venv|alembic|tests|__pycache__)/.*|__init__.py'
        args: [ --remove-all-unused-imports, --recursive, --remove-unused-variables, --in-place ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [ python ]
        exclude: '(venv|alembic|tests|__pycache__)/.*|__init__.py'
        args: [ --multi-line=3, --trailing-comma, --force-grid-wrap=0, --use-parentheses, --ensure-newline-before-comments, --line-length=120 ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        types: [ python ]
        exclude: '(venv|alembic|tests|__pycache__)/.*|__init__.py'
        args: [ --line-length=120, --target-version=py38, --skip-string-normalization ]

  - repo: local
    hooks:

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        exclude: '(venv|alembic|tests|__pycache__)/.*|__init__.py'
        types: [ python ]
        args: [ ]
