repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        args: [ --remove-all-unused-imports, --recursive, --remove-unused-variables, --in-place, --exclude=__init__.py ]

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        args: [ ]

      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        args: [ ]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        args: [ ]
